name: Android Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and test with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug testDebug

    - name: Upload APK debug artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/
